version: "3.9"

services:
  api:
    build: ./back
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./back:/app

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: thevampirediaries
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build: ./front/characters-tvd
    container_name: frontend_app
    ports:
      - "3000:80"
    depends_on:
      - api

  db_init:
    build:
      context: ./back
    command: python db_init.py
    depends_on:
      - db
      - api
    restart: "no"
    env_file:
      - .env

volumes:
  mysql_data:
